apiVersion: batch/v1
kind: Job
metadata:
  name: {{jobname|default("demo-job")}}
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: demo-job
        image: perl
        command: ["perl",  "-E", 'STDOUT->autoflush(1); $str = "The quick brown fox jumps over the lazy dog   -50-"; for ($i = 1; $i <= {{iterations|default(5)}}; $i++) { printf "%04d $str \n", $i; sleep({{delay|default(10)}}) }']
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  {% if ttlseconds -%}
  ttlSecondsAfterFinished: {{ttlseconds}}
  {% endif -%}
  backoffLimit: 4

